// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/blockchain.proto

package blockchain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetIssueRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIssueRequest) Reset()         { *m = GetIssueRequest{} }
func (m *GetIssueRequest) String() string { return proto.CompactTextString(m) }
func (*GetIssueRequest) ProtoMessage()    {}
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f4b4ddece70981, []int{0}
}

func (m *GetIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIssueRequest.Unmarshal(m, b)
}
func (m *GetIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIssueRequest.Marshal(b, m, deterministic)
}
func (m *GetIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIssueRequest.Merge(m, src)
}
func (m *GetIssueRequest) XXX_Size() int {
	return xxx_messageInfo_GetIssueRequest.Size(m)
}
func (m *GetIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIssueRequest proto.InternalMessageInfo

type GetIssueResponse struct {
	Puzzle               []byte   `protobuf:"bytes,1,opt,name=puzzle,proto3" json:"puzzle,omitempty"`
	Complexity           int32    `protobuf:"varint,2,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIssueResponse) Reset()         { *m = GetIssueResponse{} }
func (m *GetIssueResponse) String() string { return proto.CompactTextString(m) }
func (*GetIssueResponse) ProtoMessage()    {}
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f4b4ddece70981, []int{1}
}

func (m *GetIssueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIssueResponse.Unmarshal(m, b)
}
func (m *GetIssueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIssueResponse.Marshal(b, m, deterministic)
}
func (m *GetIssueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIssueResponse.Merge(m, src)
}
func (m *GetIssueResponse) XXX_Size() int {
	return xxx_messageInfo_GetIssueResponse.Size(m)
}
func (m *GetIssueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIssueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIssueResponse proto.InternalMessageInfo

func (m *GetIssueResponse) GetPuzzle() []byte {
	if m != nil {
		return m.Puzzle
	}
	return nil
}

func (m *GetIssueResponse) GetComplexity() int32 {
	if m != nil {
		return m.Complexity
	}
	return 0
}

func (m *GetIssueResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetQuoteRequest struct {
	Solution             []byte   `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteRequest) Reset()         { *m = GetQuoteRequest{} }
func (m *GetQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuoteRequest) ProtoMessage()    {}
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f4b4ddece70981, []int{2}
}

func (m *GetQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteRequest.Unmarshal(m, b)
}
func (m *GetQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteRequest.Marshal(b, m, deterministic)
}
func (m *GetQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteRequest.Merge(m, src)
}
func (m *GetQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuoteRequest.Size(m)
}
func (m *GetQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteRequest proto.InternalMessageInfo

func (m *GetQuoteRequest) GetSolution() []byte {
	if m != nil {
		return m.Solution
	}
	return nil
}

func (m *GetQuoteRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetQuoteResponse struct {
	Quote                string   `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteResponse) Reset()         { *m = GetQuoteResponse{} }
func (m *GetQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuoteResponse) ProtoMessage()    {}
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f4b4ddece70981, []int{3}
}

func (m *GetQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteResponse.Unmarshal(m, b)
}
func (m *GetQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteResponse.Marshal(b, m, deterministic)
}
func (m *GetQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteResponse.Merge(m, src)
}
func (m *GetQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuoteResponse.Size(m)
}
func (m *GetQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteResponse proto.InternalMessageInfo

func (m *GetQuoteResponse) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func init() {
	proto.RegisterType((*GetIssueRequest)(nil), "blockchain_service.GetIssueRequest")
	proto.RegisterType((*GetIssueResponse)(nil), "blockchain_service.GetIssueResponse")
	proto.RegisterType((*GetQuoteRequest)(nil), "blockchain_service.GetQuoteRequest")
	proto.RegisterType((*GetQuoteResponse)(nil), "blockchain_service.GetQuoteResponse")
}

func init() { proto.RegisterFile("protobuf/blockchain.proto", fileDescriptor_08f4b4ddece70981) }

var fileDescriptor_08f4b4ddece70981 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x96, 0x96, 0x76, 0x10, 0xac, 0x8b, 0x48, 0xec, 0x41, 0x42, 0xf4, 0x90, 0x53,
	0x02, 0x7a, 0x96, 0x62, 0x2e, 0xe2, 0xd1, 0x5c, 0x04, 0x11, 0x4a, 0x12, 0x47, 0xb3, 0xb8, 0xcd,
	0xa4, 0xd9, 0xdd, 0xa2, 0xfd, 0x71, 0xfe, 0x36, 0xc9, 0x36, 0x69, 0xa2, 0xd2, 0xde, 0x76, 0xde,
	0xee, 0x7e, 0xf3, 0xde, 0x0c, 0x9c, 0x17, 0x25, 0x29, 0x4a, 0xf4, 0x5b, 0x90, 0x08, 0x4a, 0x3f,
	0xd2, 0x2c, 0xe6, 0xb9, 0x6f, 0x34, 0xc6, 0x5a, 0x65, 0x21, 0xb1, 0x5c, 0xf3, 0x14, 0xdd, 0x13,
	0x38, 0xbe, 0x47, 0xf5, 0x20, 0xa5, 0xc6, 0x08, 0x57, 0x1a, 0xa5, 0x72, 0x5f, 0x60, 0xda, 0x4a,
	0xb2, 0xa0, 0x5c, 0x22, 0x3b, 0x83, 0x51, 0xa1, 0x37, 0x1b, 0x81, 0xb6, 0xe5, 0x58, 0xde, 0x51,
	0x54, 0x57, 0xec, 0x02, 0x20, 0xa5, 0x65, 0x21, 0xf0, 0x93, 0xab, 0x2f, 0xbb, 0xef, 0x58, 0xde,
	0x30, 0xea, 0x28, 0x6c, 0x0a, 0x03, 0xcd, 0x5f, 0xed, 0x81, 0x63, 0x79, 0x93, 0xa8, 0x3a, 0xba,
	0x73, 0xd3, 0xf0, 0x51, 0x93, 0x6a, 0x1a, 0xb2, 0x19, 0x8c, 0x25, 0x09, 0xad, 0x38, 0xe5, 0x35,
	0x7e, 0x57, 0x37, 0x80, 0x7e, 0x0b, 0xf0, 0x8c, 0xbd, 0x1a, 0x50, 0xdb, 0x3b, 0x85, 0xe1, 0xaa,
	0x12, 0xcc, 0xf7, 0x49, 0xb4, 0x2d, 0xae, 0xbf, 0x2d, 0x80, 0x70, 0x17, 0x99, 0x3d, 0xc1, 0xb8,
	0xc9, 0xc5, 0x2e, 0xfd, 0xff, 0xb3, 0xf0, 0xff, 0x0c, 0x62, 0x76, 0x75, 0xf8, 0xd1, 0xb6, 0xb7,
	0xdb, 0xab, 0xc1, 0xc6, 0xd1, 0x5e, 0x70, 0x37, 0xf0, 0x5e, 0xf0, 0xaf, 0x50, 0x6e, 0x2f, 0x9c,
	0x3f, 0xdf, 0xbe, 0x73, 0x95, 0xe9, 0xc4, 0x4f, 0x69, 0x19, 0xdc, 0x95, 0x4a, 0x97, 0x61, 0x2c,
	0x62, 0x99, 0xd1, 0xba, 0xb3, 0xdd, 0x05, 0xaf, 0xfc, 0x04, 0x3c, 0x57, 0x58, 0xe6, 0xb1, 0xe8,
	0xdc, 0x24, 0x23, 0xb3, 0xf8, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0x0a, 0xce, 0x99,
	0x15, 0x02, 0x00, 0x00,
}
